### ISSUE TITLE
Z offset reset 

### ISSUE THREAD

**Issue by monoque** [FracktalWorks/Julia3GTouchUI#2]
the z offset value resets on accidentally clicking on the bed leveling wizard. Z offset doesnt have to be a part of the wizard at all. A value of 0.6mm works very well.

**Comment by vjvarada** [comment]
I shall remove Z offset itself.

**Comment by vjvarada** [comment]
You will need to set 0.6 as the default when the printer starts for the first time. I shall add it as a part of the MKS code as well, and generate new hex file which will be available at https://github.com/FracktalWorks/Julia3GMarlin/tree/master/Hex
